### ISSUE TITLE
Laradumps for Apple Silicon (ARM)

### ISSUE THREAD

**Issue by tariktokic** [laradumps/app#128]
Hi!

Is there any chance to get a build for Apple Silicon Macs? 
There is Electron Support https://www.electronjs.org/blog/apple-silicon/

If can help by compiling on the M1 mac, so please let me know.

**Comment by tariktokic** [comment]
You are right @luanfreitasdev 

Now, executing 'sudo npm install' I get the some warnings, followed by an 404 error


> npm ERR! code 1
> npm ERR! path /app-main/node_modules/electron-tray-window/node_modules/electron
> npm ERR! command failed
> npm ERR! command sh -c node install.js
> Downloading tmp-92419-0-electron-v3.1.13-darwin-arm64.zip
> **npm ERR! Error: GET https://github.com/electron/electron/releases/download/v3.1.13/electron-v3.1.13-darwin-arm64.zip** returned 404
> npm ERR! /app-main/node_modules/electron-tray-window/node_modules/electron/install.js:49
> npm ERR!   throw err
> npm ERR!   ^
> npm ERR! 
> **npm ERR! Error: Failed to find Electron v3.1.13 for darwin-arm64 at https://github.com/electron/electron/releases/download/v3.1.13/electron-v3.1.13-darwin-arm64.zip**
> npm ERR!     at Request.<anonymous> (/app-main/node_modules/nugget/index.js:169:61)
> npm ERR!     at Request.emit (node:events:513:28)
> npm ERR!     at Request.onRequestResponse (/app-main/node_modules/request/request.js:1059:10)
> npm ERR!     at ClientRequest.emit (node:events:513:28)
> npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:686:27)
> npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
> npm ERR!     at TLSSocket.socketOnData (node:_http_client:528:22)
> npm ERR!     at TLSSocket.emit (node:events:513:28)
> npm ERR!     at addChunk (node:internal/streams/readable:324:12)
> npm ERR!     at readableAddChunk (node:internal/streams/readable:297:9)
> npm ERR! 
> npm ERR! Node.js v19.1.0

**Comment by luanfreitasdev** [comment]
Can you remove that package from npm and try again?

electron-tray-window

**Comment by tariktokic** [comment]
After fixing some problems related to the file rights, now I have an working version!
Startup time has reduced a lot!

FYI: https://github.com/laradumps/app/issues/129 is still present. Is this related to electron-tray-window?

**Comment by luanfreitasdev** [comment]
How nice!, can you open a pr to generate universal?

Would you like to translate to German? I don't know if it's possible to do something simple with vanilla

**Comment by tariktokic** [comment]
> How nice!, can you open a pr to generate universal?

I think, I don't quite understand ;-)
Do you want me to open a pr an upload the universal? Can you give me some more instructions please?

> Would you like to translate to German? I don't know if it's possible to do something simple with vanilla

Yes, why not. On the other hand, it won't work with vanilla, I agree. This would mean more work for you to implement some i18n structure?

**Comment by luanfreitasdev** [comment]
> > How nice!, can you open a pr to generate universal?
> 
> I think, I don't quite understand ;-) Do you want me to open a pr an upload the universal? Can you give me some more instructions please?
> 
> > Would you like to translate to German? I don't know if it's possible to do something simple with vanilla
> 
> Yes, why not. On the other hand, it won't work with vanilla, I agree. This would mean more work for you to implement some i18n structure?

I don't think this is a good idea right now. Soon we will release a version that can support.
