### ISSUE TITLE
[BUG] Shotcut bug

### ISSUE THREAD

**Issue by allanmcarvalho** [laradumps/app#129]
## Information
On MacOs when command+Q is pressed Laradumps try to quit while out of focus. I am using 1.4.0 version on last version of macOs monterey (12.6) on a x86 cpu.

### Pre-steps
Open laradumps on MacOs, change the program focus for another program, and press command+Q, laradamps will ask the quit confirmation.

#### Have you searched through other issues to see if your problem is already reported or has been fixed?

- [x] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://laradumps.dev/)?

- [ ] Yes - I did not find it.
- [x] No

**Comment by tariktokic** [comment]
Hi @dansysanalyst !
This bug is really driving me crazy, as any time I want to close and running app via "command + w", LaraDumps gets the focus. 
Do you have any estimation, in which release this will be fixed?

Thank you so much for your work on this great helper!

**Comment by allanmcarvalho** [comment]
In fact, I stoped use it until the solution for this bug... It is very painful.

**Comment by luanfreitasdev** [comment]
Hi!. Could you record a video demonstrating? I'm trying to reproduce the problem, but haven't found one yet.

**Comment by dansysanalyst** [comment]
Hi @allanmcarvalho and @tariktokic,

I believe the PR will resolve the issue.

Thanks for the patience and reminders, I've been caught at a big work project ☺️

**Comment by luanfreitasdev** [comment]
Thanks @dansysanalyst
