### ISSUE TITLE
Please add shortcuts for everything

### ISSUE THREAD

**Issue by iammayron** [laradumps/app#130]
# 🛻 LaraDumps Feature Request

## Summary

I think it is important to have quick keyboard shortcuts for every important button in the app, like clean log, change screen, etc...

### Why is this needed?

You might know that we developers work more with our keyboard than our mouse, so moving the mouse from my coding application or browser to the laradumps app just to clear the logs during a debug session is so annoying because you have to do that so many times.

### Suggested Solution(s)

- Add shortcuts to be used while the active window is the Laradumps so it can be any shortcut
- Add shortcuts that will be listened even if the active window is another window like the PHPStorm window or other, so the person doesn't need to change the window (global shortcuts)

### Related issue(s)/PR(s)

Let us know if this is related to any issue/request

**Comment by luanfreitasdev** [comment]
Hello @iammayron , It is available in version 2.0. Thanks for the suggestion
![image](https://github.com/laradumps/app/assets/33601626/01188329-d17b-48f3-bf4e-eb0f27f280cf)

https://github.com/laradumps/app/releases/tag/v2.0.0
