### ISSUE TITLE
Keyboard shortcuts conflicts with vscode

### ISSUE THREAD

**Issue by goper-leo** [laradumps/app#240]
Issue when laradumps app is opened and focus on editor (vscode), Laradumps will catch keyboard shortcuts.

This issue was only introduced after [1.7.2](https://github.com/laradumps/app/releases/tag/v1.7.2). 

Thanks for this wonderful tool! It is very helpful.

### How to replicate:

- Open Laradumps app
- Open vscode
- Add keyboard shortcuts that is the same with the Laradumps KB shortcuts (mine was `Ctrl+D` which is toggling Dark/Light Mode)
- Focus on vscode
- Press `Ctrl+D`
- Even `Laradumps` is not focused it will toggle (Dark/Light mode). Worst that KB will not trigger vscode commands

Environment:
`Ubuntu 22.04`
Laradumps Desktop: `2.0.2`
VSCODE
```
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:59:55.818Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-46-generic snap
```
Laravel: `v10.13.5`
`laradumps/laradumps`: `v2.0.0`

**Comment by luanfreitasdev** [comment]
Hello!. This is the default utility for global shortcuts (should work in any state of the app). I suggest changing the shortcuts according to the need
