### ISSUE TITLE
Showing blank logs

### ISSUE THREAD

**Issue by devduttabain** [laradumps/app#245]
![image](https://github.com/laradumps/app/assets/7148042/42c72101-df18-48a6-9bbb-82e1bec656d3)

can see screen refreshing when executing the code, but nothing showing on the app.

PHP 8.1.19
Laravel Framework 8.83.27
laradumps/laradumps 1.12
laradumps/app 2.1.2

**Comment by luanfreitasdev** [comment]
Hello!. Please see #244
