### ISSUE TITLE
App now working(

### ISSUE THREAD

**Issue by igor-d-n** [laradumps/app#250]
Not working on linux - trying to show data but only empty divs
Not working on windows - don't receive any data at all

**Comment by luanfreitasdev** [comment]
Hello. Please give more details. What version of the composer package and app are you using?

**Comment by Geoffry304** [comment]
@luanfreitasdev  app is not working for me either, i work with docker and before I did the update everything was working.
I am on app version 2.1.3  and composer package version "laradumps/laradumps": "^2.1"

This is my env file

`
DS_APP_HOST=app_timedesk-laravel
DS_INSTALLED=true

DS_AUTO_CLEAR_ON_PAGE_RELOAD=true
DS_AUTO_INVOKE_APP=false
DS_SEND_COLOR_IN_SCREEN=false
DS_SEND_QUERIES=false
DS_SEND_LOGS_APPLICATIONS=false
DS_SEND_LOGS_VENDOR=false
DS_SEND_HTTP_CLIENT_REQUESTS=false
DS_SEND_JOBS=false
DS_SEND_CACHE=false
DS_SEND_COMMANDS=false
DS_SEND_HTTP=false
DS_SEND_SCHEDULED_COMMANDS=false
DS_SEND_GATE=false
DS_SEND_LOGS_DEPRECATED=false
DS_SEND_MAIL=false
DS_FILE_HANDLER=phpstorm://open?file={filepath}&line={line}
DS_PROJECT_PATH=<Leads to my project>
`

**Comment by luanfreitasdev** [comment]
Hello @Geoffry304 . Can you record a video?

**Comment by Geoffry304** [comment]
Yeah no problem can I send it in a dm or something?

**Comment by Geoffry304** [comment]
https://tempclip.com/XQRduZATy9nUGXM/watch
[https://tempclip.com/images/social-image.jpg]<https://tempclip.com/XQRduZATy9nUGXM/watch>
TempClip — Watch — screencast 2023-07-13 21-11-41.mp4<https://tempclip.com/XQRduZATy9nUGXM/watch>
Upload and share your temporary video with a link. Password protect your temporary videos. Set a time limit on your temporary video uploads.
tempclip.com

________________________________
Van: Luan Freitas ***@***.***>
Verzonden: donderdag 13 juli 2023 20:59
Aan: laradumps/app ***@***.***>
CC: Geoffry Van den Eede ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [laradumps/app] App now working( (Issue #250)


Hello @Geoffry304<https://github.com/Geoffry304> . Can you record a video?

**Comment by luanfreitasdev** [comment]
Can you send me via twitter or email?

https://twitter.com/luanfreitasdev 
luanfreitas10@protonmail.com

**Comment by Geoffry304** [comment]
Ok I mailed you the link

**Comment by SkiperX** [comment]
I also encountered a problem

https://prnt.sc/uOjKxLuhj_j2

**Comment by jaspersmitNL** [comment]
For me the app shows a white screen when opening.
<img width="871" alt="image" src="https://github.com/laradumps/app/assets/24923076/3da22e8c-1000-4ba7-9bdd-75e19f71b58a">

**Comment by nick322** [comment]
> For me the app shows a white screen when opening. <img alt="image" width="871" src="https://user-images.githubusercontent.com/24923076/280975303-3da22e8c-1000-4ba7-9bdd-75e19f71b58a.png">

I also encountered this problem. At first, I installed v2.4.0 directly, and then I modified the old version.
https://github.com/laradumps/app/releases/tag/v2.3.3
Then the correct screen appears in v2.3.3, and then upgrade to v2.4.0
for your information.

**Comment by luanfreitasdev** [comment]
So it's not working in version 2.4? Which OS do you use?. I haven't had this problem yet to fix it. It would be good if you tried to do a local build to try to discover the origin 😀

**Comment by ferdousanam** [comment]
> So it's not working in version 2.4? Which OS do you use?. I haven't had this problem yet to fix it. It would be good if you tried to do a local build to try to discover the origin 😀

I have also same problem. I am using windows 11.

**Comment by pakogn** [comment]
Using Ubuntu 22.04 and is not working. Currently using v2.4.0

Even with 2.3.3 is not working. It always shows this:

![image](https://github.com/laradumps/app/assets/9632858/378789ec-7e96-495a-8056-53ee74317cf3)


Do i need to do something special?
