### ISSUE TITLE
Please disable "Are you sure you want to quit?" dialogue when terminating the app.

### ISSUE THREAD

**Issue by tariktokic** [laradumps/app#252]
This is not an issue, just one wish: when quitting the app (macOS), can you please disable this question or at least make it optional in settings? The standard in macOS is not no ask users when they want to quit - you just terminate the app.

Thank you!

<img width="302" alt="Bildschirmfoto 2023-08-08 um 09 02 07" src="https://github.com/laradumps/app/assets/22153538/e8710ba3-4b9b-4db2-9b9c-1fe67fe36d17">

**Comment by luanfreitasdev** [comment]
Hi, can you send a pull request?
