### ISSUE TITLE
Javascript error - Attemping to read 'laradumps_version'

### ISSUE THREAD

**Issue by VincentVanWijk** [laradumps/app#254]
Sometimes i get this error immediatly after my first dump, sometimes it works for several hours before it shows up, but it always does eventually. 

![image](https://github.com/laradumps/app/assets/10919865/6694e03a-549c-4c3f-9046-6e4720372f41)

**Comment by jpdroid** [comment]
The same error is showing up for me.

**Comment by luanfreitasdev** [comment]
Hello!. Let me know which php package and which version. Thanks
