### ISSUE TITLE
Clicking File link, App Goes Blank

### ISSUE THREAD

**Issue by devduttabain** [laradumps/app#257]
![image](https://github.com/laradumps/app/assets/142681510/0f48f251-13b1-465b-a92b-e15cc943e546)

### Clicking File link App Goes Blank

![image](https://github.com/laradumps/app/assets/142681510/0a2edd6a-580b-42f3-bc7c-24bb8608602c)

### Info
OS: Windows 11
App Version: 2.3.1
Composer Package Version: v2.1.0

**Comment by devduttabain** [comment]
Is there any settings I have to put in .env for editor?

BTW, my editor is vscode.

**Comment by Lorrhanl** [comment]
It's the same problem with Linux, but I don't need to touch in file or use ds in my code for the screen to go blank, after opening the app in a few seconds it happens.

![image](https://github.com/laradumps/app/assets/22606611/435cabb6-e0b0-4873-9bca-0ae94138ed19)

![image](https://github.com/laradumps/app/assets/22606611/2c8e2241-778a-424b-90c5-dcf1f7fccdb8)

OS: Manjaro
Composer: "laradumps/laradumps": "^2.2"
App Version: 2.3.2

I'm using Laravel sail in my project, It's my config:

DS_APP_HOST=host.docker.internal
DS_INSTALLED=true

DS_AUTO_CLEAR_ON_PAGE_RELOAD=false
DS_AUTO_INVOKE_APP=false
DS_SEND_COLOR_IN_SCREEN=
DS_SEND_QUERIES=false
DS_SEND_LOGS_APPLICATIONS=false
DS_SEND_LOGS_VENDOR=false
DS_SEND_HTTP_CLIENT_REQUESTS=false
DS_SEND_JOBS=false
DS_SEND_CACHE=false
DS_SEND_COMMANDS=false
DS_SEND_HTTP=false
DS_SEND_MAIL=false
DS_SEND_SCHEDULED_COMMANDS=false
DS_SEND_GATE=false
DS_FILE_HANDLER=vscode://file/{filepath}:{line}
DS_PROJECT_PATH=

It was working in version 1

**Comment by YannickYayo** [comment]
Any update on this ?
I have the same issue, on Linux Manjaro, the app goes blank after a few seconds :(

**Comment by luanfreitasdev** [comment]
Looking at this. I haven't been able to reproduce the problem yet. If you want to open a PR, we can advance this issue! Thanks

**Comment by luanfreitasdev** [comment]
In version 3, this will be configured directly in the application. Please wait for the release.

Thank you
