### ISSUE TITLE
Desktop app sidebar not visible

### ISSUE THREAD

**Issue by meronivalerio** [laradumps/app#263]
Hi, I can't see the sidebar on my app.
App Version: 2.4.0
OS: macOS Sonoma 14.1.1

![Screenshot 2023-11-27 alle 08 19 25](https://github.com/laradumps/app/assets/7338751/a70ab4f0-b093-4eb7-85f8-b6396477cf4b)

**Comment by meronivalerio** [comment]
Works on version 2.3.3

**Comment by luanfreitasdev** [comment]
Hello! Can you run it in development mode so we can try to capture the problem? I haven't been able to reproduce this bug yet on macOS

**Comment by meronivalerio** [comment]
Let me know if the steps I followed are correct:
- clone the project
- yarn install
- yarn dev
- yarn electron

this is the result:

![Screenshot 2023-11-27 alle 13 50 05](https://github.com/laradumps/app/assets/7338751/2ab2045f-c2d6-4154-9dec-66ac2b1c6866)

Thanks

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/laradumps/app/issues/265
