### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LeoMachado94** [laradumps/app#265]
O cliente v2.4.0 não está executando no MacOS, estou tentando faz 2 dias e nada..
<img width="1144" alt="image" src="https://github.com/laradumps/laradumps/assets/11590935/699ddc49-92f8-458b-8329-edd0faa9b9ca">

Versao anterior..
<img width="1144" alt="image" src="https://github.com/laradumps/laradumps/assets/11590935/51a8eca4-7d25-4c1f-b68f-7966a33e9d87">

**Comment by gabrielphilipes** [comment]
@luanfreitasdev realizei o mesmo procedimento: 
1. Desinstalei completamente a versão anterior;
2. Baixei o ZIP, do link acima;
3. Instalei e dei as permissões necessárias.

Mas ainda não rodou rs a tela em branco persiste. Estou utilizando um Mac M1. Acredita que seja por isso? Tentei rodá-lo pelo Rosetta, mas o app nem abriu.

<img width="782" alt="Screenshot 2023-12-03 at 13 02 23" src="https://github.com/laradumps/app/assets/48845302/b2f00c3a-28c0-453d-bff5-7f26e15b3b80">

**Comment by luanfreitasdev** [comment]
Que estranho. Você consegue fazer o pull da branch e executar localmente ? Preciso de mais informações pois isso ainda não aconteceu com algumas pessoas

**Comment by LeoMachado94** [comment]
@luanfreitasdev assim que eu testar aviso aqui também
