### ISSUE TITLE
Even with 2.4.1 is not working in Ubuntu

### ISSUE THREAD

**Issue by pakogn** [laradumps/app#268]
While trying to configure Laradumps in cli it says:

Is the LaraDumps Application open?

I use the AppImage. and I have Ubuntu 22.04.3 x64

what's missing?

thanks!

**Comment by cirino** [comment]
Na atual versão, parou de funcionar no Ubuntu / WSL. Travado na tela de configuração 'vendor/bin/laradumps configure' sem nenhuma alteração.
![image](https://github.com/laradumps/app/assets/204371/0471e2a7-d683-4e4a-8e00-8d9e15adaffa)

![image](https://github.com/laradumps/app/assets/204371/060874ad-90df-4770-bda2-73e5f458f1f8)

**Comment by luanfreitasdev** [comment]
See https://github.com/laradumps/laradumps/issues/121#issuecomment-1965468070
