### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by Ham3D** [laradumps/app#275]
there is a performance issue with desktop App.

i have installed laradump, on a big application, which there are Lots of Log generated with each request.
also activated all options (show queries, logs, etc.)

then desktop app Froze after some seconds.

im on M2 mac.

**Comment by luanfreitasdev** [comment]
Hello. We do not recommend using all features at the same time, as this will likely result in performance problems, not only in laradumps but in any other debugger.

Try to solve specific problems, such as activating the log only when you want to see the log. Activate queries on a specific page or specific block.

**Comment by Ham3D** [comment]
i see you reasoning here, but that is a problem that can be fixed. 
We have beefy machines that can handle that load of data.
maybe keep this in backlog and get to it sometimes later.
or give some hints, maybe someone is up for the PR
