### ISSUE TITLE
Logs dont show on Brand new installation

### ISSUE THREAD

**Issue by nagi1** [laradumps/app#277]
![image](https://github.com/laradumps/app/assets/16584220/585422c1-5224-40a8-a42e-f402ad93f77a)

I arleady check the docs and this [ticket as well](https://github.com/laradumps/app/issues/265)

DS_APP_HOST=127.0.0.1
DS_INSTALLED=true

DS_AUTO_CLEAR_ON_PAGE_RELOAD=false
DS_AUTO_INVOKE_APP=false
DS_SEND_COLOR_IN_SCREEN=true
DS_SEND_QUERIES=false
DS_SEND_LOGS_APPLICATIONS=true
DS_SEND_LOGS_VENDOR=false
DS_SEND_HTTP_CLIENT_REQUESTS=false
DS_SEND_JOBS=false
DS_SEND_CACHE=true
DS_SEND_COMMANDS=false
DS_SEND_HTTP=false
DS_SEND_SCHEDULED_COMMANDS=false
DS_SEND_GATE=false
DS_SEND_LOGS_DEPRECATED=false
DS_SEND_MAIL=true
DS_FILE_HANDLER=vscode://file/{filepath}:{line}
DS_PROJECT_PATH=

M2 Macos

**Comment by luanfreitasdev** [comment]
Hello!. This has been fixed in version 3.0 which will soon be released. 
I'm happy to receive feedback afterward. 

Thanks!
