### ISSUE TITLE
Blank screen on Intel Mac 14.4.1 (23E224)

### ISSUE THREAD

**Issue by andruu** [laradumps/app#281]
When opening I'm getting this blank screen, followed all the new installation instructions. Let me know if you need anymore information.

![CleanShot 2024-03-30 at 08 23 51@2x](https://github.com/laradumps/app/assets/150730/1dc82903-0541-4101-95d9-f98715b90beb)

**Comment by luanfreitasdev** [comment]
Thank you for reporting this issue, it helps the community a lot.

I managed to identify this on Linux Debian. I believe it is the same case (even for me working on macOS).

Fixed in version **3.0.1**, if you persist you can open it again

Thanks!
