### ISSUE TITLE
v3 - Double click collapse

### ISSUE THREAD

**Issue by Krato** [laradumps/app#283]
Hi!

After the latest upgrade to v3, it's impossible to select fields or values by double-clicking. It collapses automatically.

Thank you!

**Comment by luanfreitasdev** [comment]
Hello! Can you send the PR ? The logic is in DumpItem.vue

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/laradumps/app/releases/tag/v3.0.2

**Comment by Krato** [comment]
> Fixed: https://github.com/laradumps/app/releases/tag/v3.0.2

Thank you :)
