### ISSUE TITLE
Difficult to read dumps, the font weight is too light and contrast too low (on PopOS)

### ISSUE THREAD

**Issue by ghost** [laradumps/app#286]
# 🛻 LaraDumps Feature Request

## Summary

It is difficult to read what is being shown (with every theme, light and dark). 

### Why is this needed?

To make it easier to read what is in the debug window

### Suggested Solution(s)

Increase the font weight and make the color darker/lighter depending on the theme.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/request

![Screenshot from 2024-04-06 17-23-34](https://github.com/laradumps/laradumps/assets/79835509/a3cf6abd-7e25-4f08-a634-0c8ae1027861)

**Comment by luanfreitasdev** [comment]
I've had difficulties using Laradumps in PopOs in previous versions. Since the theme changed to daisy, let's invest in that. 

Thanks for the report

**Comment by ghost** [comment]
Thank you for making this app, very happy with it otherwise!

Arrays look fine (just fyi.)

![Screenshot from 2024-04-06 18-04-28](https://github.com/laradumps/app/assets/79835509/9861897d-54b6-493f-95e7-22f0ca933283)

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/laradumps/app/releases/tag/v3.0.3

**Comment by ghost** [comment]
Thanks a bunch! This will make it more readable :)

![Screenshot from 2024-04-10 11-59-46](https://github.com/laradumps/app/assets/79835509/992e9753-d959-43af-aa85-97f5a8088528)
