### ISSUE TITLE
Continuous Prompt for LaraDumps Package Update Despite Acknowledgment

### ISSUE THREAD

**Issue by vildanbina** [laradumps/app#291]
Currently, on Windows 11 with the LaraDumps app installed, there seems to be an unexpected behavior. Upon utilizing the `ds()` call, a dialog prompt appears, notifying about a LaraDumps package update availability. Despite clicking "OK" to acknowledge the update, the prompt keeps reappearing with every `ds()` call.

Expected Behavior:
The LaraDumps package update prompt should only appear once, and subsequent occurrences should be suppressed after acknowledgment. 

Steps to Reproduce:
1. Install LaraDumps app on Windows 11.
2. Utilize the `ds()` call in a Laravel project.
3. Observe the continuous appearance of the LaraDumps package update prompt with each `ds()` call.

Additional Information:
- Operating System: Windows 11
- LaraDumps Package Version: ^3.0
- Laravel Project Version: ^10.0
- Reproducibility: Consistently occurs with each `ds()` call.

This issue disrupts workflow and may lead to inconvenience for users. Any insights or resolutions on resolving this matter would be greatly appreciated. Thank you.

**Comment by luanfreitasdev** [comment]
Hello. Can you send a screenshot of laradumps with the modal open? This behavior is standard in laradumps in all calls to prevent using the app if it is outdated. But there seems to be a problem in your case. What version of laradumps-core was installed?

**Comment by vildanbina** [comment]
Hi @luanfreitasdev, thanks for your quick response

![image](https://github.com/laradumps/app/assets/51203303/0a76fce0-e6d7-4f38-9321-e3f1b92bf1f3)

Here it is, also in this project these are the package versions:
```
"laradumps/laradumps": "3.0",
"laradumps/laradumps-core": "2.0",
```
It's also worth noting that I've reinstalled the app, but the situation remains the same.

**Comment by luanfreitasdev** [comment]
If you update the dependencies, will this still happen?

`composer require laradumps/laradumps --dev -W`

**Comment by vildanbina** [comment]
yeah, I've updated both based on the modal, but it still persist
