### ISSUE TITLE
Respect auto-launch settings.

### ISSUE THREAD

**Issue by andruu** [laradumps/app#296]
Everytime I restart the app it adds itself back to my Login Items. I've tried using the auto-launch settings and it still shows up with each relaunch of the app.
![CleanShot 2024-05-26 at 09 10 17@2x](https://github.com/laradumps/app/assets/150730/1d1456a1-a757-43e5-b073-edcfd9e4117b)
![CleanShot 2024-05-26 at 09 10 52@2x](https://github.com/laradumps/app/assets/150730/c6932167-4c43-474a-ae6e-96715e1b5827)

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/laradumps/app/releases/tag/v3.2.4

Thanks!
