### ISSUE TITLE
Cmd+Shift+X is used in vscode to open extensions and it gets hijacked by Laradumps

### ISSUE THREAD

**Issue by andruu** [laradumps/app#306]
# 🛻 LaraDumps Feature Request

## Summary

Cmd+Shift+X is used in vscode to open extensions and it gets hijacked by Laradumps.

Brief description of what is at stake.

Can't open extensions with default hotkey

### Why is this needed?

A clear and concise description of the problem.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/request

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/laradumps/app/releases/tag/v3.3.0

Thank you
