### ISSUE TITLE
Missing delete button for the Saved Dumps

### ISSUE THREAD

**Issue by kiddtang** [laradumps/app#312]
I can't find anyway to deleted the Saved Dumps.

There is an obvious "bin" icon for clearing the outputs, but it is missing in the Saved Dump Window.

![image](https://github.com/user-attachments/assets/325972a2-49df-44d8-b34e-86e1ed8e973f)

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/laradumps/app/releases/tag/v3.3.5

To delete a record, right-click and click "remove"
