### ISSUE TITLE
[Feature Request]Display XML content

### ISSUE THREAD

**Issue by shiroamada** [laradumps/app#343]
Hi, Is it possible to display XML structure content, like Ray?

check it is an XML structure or Node, it have the display.

<img width="1049" alt="image" src="https://github.com/user-attachments/assets/5e46ed3a-4ac6-4efc-9b60-5073abac2e4d">

Thanks

**Comment by dansysanalyst** [comment]
@luanfreitasdev, I think it would be better to not render HTML. This might be inconvenient when trying to debug an HTML response or even a XML string:

```php
ds('
<?xml version="1.0" encoding="UTF-8" ?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03">
    <CstmrCdtTrfInitn>
        <GrpHdr>
            <MsgId>Message-Id</MsgId>
            <CreDtTm>2024-05-10T16:10:02.017+00:00</CreDtTm>
            <NbOfTxs>1</NbOfTxs>
') //...

ds('<span style="color: red">red</span><br>line break');
```

![CleanShot 2024-12-04 at 14 27 08@2x](https://github.com/user-attachments/assets/4282a873-9e7e-459e-bfa9-d632d2db1fc9)

**Comment by dansysanalyst** [comment]
Issue solved in https://github.com/laradumps/app/pull/353

![CleanShot 2024-12-11 at 10 18 48@2x](https://github.com/user-attachments/assets/3a26a472-bff0-436a-b18c-90ca7086fbe9)
