### ISSUE TITLE
Logging is not showing content with the latest release

### ISSUE THREAD

**Issue by andruu** [laradumps/app#352]
![CleanShot 2024-12-09 at 15 08 06@2x](https://github.com/user-attachments/assets/3e21b05d-6529-4d92-ae6c-0a045f4eb116)

It shows context like file and line but the actual log itself does not show.

**Comment by luanfreitasdev** [comment]
Fixed https://github.com/laradumps/app/pull/353, thank you @andruu for this report

**Comment by luanfreitasdev** [comment]
Released: https://github.com/laradumps/app/releases/tag/v3.7.1
