### ISSUE TITLE
[BUG] package update process error

### ISSUE THREAD

**Issue by guhweb** [laradumps/app#90]
#### Have you searched through other issues to see if your problem is already reported or has been fixed?

- [X] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://laradumps.dev/)?

- [X] Yes - I did not find it.
- [ ] No

#### Have you tried to reconfigure LaraDumps?

To configure LaraDumps, run: `php artisan ds:init`.

- [X] Yes - I didn't work.
- [ ] No, I believe this error is not related the configuration.

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| LaraDumps App |         1.2.2         |
| LaraDumps package   |        1.2.1           |
| Laravel  |         9.19          |
| Operating System  |         macOS          |

#### What is your project Environment?

- [ ] Laravel Valet
- [X] Laravel Sail
- [ ] Docker
- [ ] XAMPP
- [ ] Laragon
- [ ] Other - please specify: ________

---

## Describe the bug

Desktop software auto-update does not work as it should.

### What happened?

I run the automatic update process, but the software does not finish by itself to complete the process, and when I manually finish it, when I load it again, the update message pops up showing that it failed to complete.

Note: Today the solution is to download the package from github manually, remove the old version and unzip the new one in the Applications directory on the mac

### Steps to Reproduce the problem

When I open a new instance of the desktop app, I get a message that there is a new version available and I want to do it now. It gives me the option to Cancel or Proceed.

When I select proceed, it opens another blank window titled laradumps, and displays an alert saying that the updates have already been downloaded and that the software needs to be closed to complete the update process.

However, when you click 'quit', nothing happens. And if I manually close the software, when I load it again, the same update message appears.

Note: I am running version 1.2.2, and indeed there is a new version available on github 1.2.5.

### Suggestions

I don't know if it could be something related to permission level on mac. I did what I could but nothing worked... I think that if something like permission is needed for this process to occur successfully, there should be some note in the official documentation.

**Screenshots**
![Screen Shot 2022-09-10 at 12 32 39 AM](https://user-images.githubusercontent.com/23559970/189467086-2cbef9b6-727f-4a4b-807d-3dfde49889da.png)

<img width="825" alt="Screen Shot 2022-09-10 at 12 32 47 AM" src="https://user-images.githubusercontent.com/23559970/189467093-2e1d346c-1123-4c0f-b294-f3b499cbe3c2.png">

<img width="825" alt="Screen Shot 2022-09-10 at 12 32 55 AM" src="https://user-images.githubusercontent.com/23559970/189467104-be273556-533c-4c8b-8d6a-1f8e43456c0a.png">

![Screen Shot 2022-09-10 at 12 33 08 AM](https://user-images.githubusercontent.com/23559970/189467111-1083034b-44b4-460b-8816-ee23eced3523.png)

**Comment by guhweb** [comment]
Using the application, another message appeared informing me that version 1.3 is now available, but on the github page I only found version 1.2.5!

![Screen Shot 2022-09-10 at 3 01 45 AM](https://user-images.githubusercontent.com/23559970/189471434-a2594fd2-b979-4a3d-8815-ed0fb417e6e7.png)

**Comment by luanfreitasdev** [comment]
> ### Pre-steps
> #### Have you searched through other issues to see if your problem is already reported or has been fixed?
> * [x]  Yes - I did not find it.
> * [ ]  No
> 
> #### Did you read the [documentation](https://laradumps.dev/)?
> * [x]  Yes - I did not find it.
> * [ ]  No
> 
> #### Have you tried to reconfigure LaraDumps?
> To configure LaraDumps, run: `php artisan ds:init`.
> 
> * [x]  Yes - I didn't work.
> * [ ]  No, I believe this error is not related the configuration.
> 
> ### Software Version
> You can run `composer show -i` and `npm list` to list installed package with their versions.
> 
> Software	Version (exactly)
> LaraDumps App	1.2.2
> LaraDumps package	1.2.1
> Laravel	9.19
> Operating System	macOS
> #### What is your project Environment?
> * [ ]  Laravel Valet
> * [x]  Laravel Sail
> * [ ]  Docker
> * [ ]  XAMPP
> * [ ]  Laragon
> * [ ]  Other - please specify: ________
> 
> ## Describe the bug
> Desktop software auto-update does not work as it should.
> 
> ### What happened?
> I run the automatic update process, but the software does not finish by itself to complete the process, and when I manually finish it, when I load it again, the update message pops up showing that it failed to complete.
> 
> Note: Today the solution is to download the package from github manually, remove the old version and unzip the new one in the Applications directory on the mac
> 
> ### Steps to Reproduce the problem
> When I open a new instance of the desktop app, I get a message that there is a new version available and I want to do it now. It gives me the option to Cancel or Proceed.
> 
> When I select proceed, it opens another blank window titled laradumps, and displays an alert saying that the updates have already been downloaded and that the software needs to be closed to complete the update process.
> 
> However, when you click 'quit', nothing happens. And if I manually close the software, when I load it again, the same update message appears.
> 
> Note: I am running version 1.2.2, and indeed there is a new version available on github 1.2.5.
> 
> ### Suggestions
> I don't know if it could be something related to permission level on mac. I did what I could but nothing worked... I think that if something like permission is needed for this process to occur successfully, there should be some note in the official documentation.
> 
> **Screenshots** ![Screen Shot 2022-09-10 at 12 32 39 AM](https://user-images.githubusercontent.com/23559970/189467086-2cbef9b6-727f-4a4b-807d-3dfde49889da.png)
> 
> <img alt="Screen Shot 2022-09-10 at 12 32 47 AM" width="825" src="https://user-images.githubusercontent.com/23559970/189467093-2e1d346c-1123-4c0f-b294-f3b499cbe3c2.png">
> 
> <img alt="Screen Shot 2022-09-10 at 12 32 55 AM" width="825" src="https://user-images.githubusercontent.com/23559970/189467104-be273556-533c-4c8b-8d6a-1f8e43456c0a.png">
> 
> ![Screen Shot 2022-09-10 at 12 33 08 AM](https://user-images.githubusercontent.com/23559970/189467111-1083034b-44b4-460b-8816-ee23eced3523.png)

Hello @guhweb , we tried to put the update by default but it didn't work as expected.

My suggestion would also be to at least warn users that there is an update, but without forcing the auto-update, but rather open the page for the user to install it manually.

**Comment by luanfreitasdev** [comment]
> Using the application, another message appeared informing me that version 1.3 is now available, but on the github page I only found version 1.2.5!
> 

About this message this is saying that app (electron) in version 1.2.2 requires your composer package (laravel) to be at least version [v1.3.0](https://github.com/laradumps/laradumps/releases/tag/v1.3.0)

**Comment by dansysanalyst** [comment]
Hi @guhweb,

Thanks for reporting the issue.

The auto-update will not work on macOS unless the application is signed and notarized.

<table>
<thead>
  <tr>
    <td>
     <p><b>Note:</b> Your application must be signed for automatic updates on macOS. This is a requirement of Squirrel.Mac.</p>
     <p>Source: <a href="https://www.electronjs.org/docs/latest/api/auto-updater">https://www.electronjs.org/docs/latest/api/auto-updater</a></td></p>
  </tr>
</thead>
</table>

Apple charges 100 USD/year for the certificate, which is super costly for LaraDumps as a free and unsponsored tool.

I have opened a PR to clarify the package update version and disable (temporarily) the macOS auto-update.

**Comment by dansysanalyst** [comment]
macOS auto-update will require LaraDumps to be signed with apple. There are no plans for that at the moment.

Users can download the latest version from the GitHub repositories or from the [official website](https://laradumps.dev/#/laravel/get-started/updating-laradumps).
